orbs:
  orb-tools: circleci/orb-tools@9.0.0
  hello-world: sample-orbs/hello-world@<<pipeline.parameters.dev-orb-version>>

parameters:
  dev-orb-version:
    default: 'dev:alpha'
    type: string
  run-integration-tests:
    default: false
    type: boolean

jobs:
  integration-tests:
    executor: hello-world/default
    steps:
      - checkout
      - hello-world/echo-command

version: 2.1
workflows:
  integration-tests_prod-release:
    jobs:
      - integration-tests
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: true
          bot-user: uraway
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          ssh-fingerprints: 1c:8c:e4:85:91:ad:0e:ee:84:fd:da:e8:1d:56:7c:e6
          orb-name: sample-orbs/hello-world
          requires:
            - integration-tests
          filters:
            branches:
              only: master
    when: << pipeline.parameters.run-integration-tests >>
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: sample-orbs/hello-world
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
    unless: << pipeline.parameters.run-integration-tests >>
